/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package program_antrian;

import java.util.LinkedList;
import java.util.Queue;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author muhammad noval aula
 */
public class AntrianApp extends javax.swing.JFrame implements program_antrian.Queue {

    private Queue<Integer> antrian = new LinkedList<>();
    private int totalAntrian = 0;
    private int panggilanNomor = 0;

    private JLabel labelJumlahAntrian;
    private JLabel labelTotalAntrian;
    private JLabel labelPanggilanNomor;
    private DefaultListModel<String> listModel;
    private JList<String> listAntrian;

    public AntrianApp() {
        setTitle("Aplikasi Antrian");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(400, 300);
        setLayout(null);

        labelJumlahAntrian = new JLabel("Jumlah Antrian: 0");
        labelJumlahAntrian.setBounds(10, 10, 150, 20);
        add(labelJumlahAntrian);

        labelTotalAntrian = new JLabel("Total Antrian: 0");
        labelTotalAntrian.setBounds(10, 40, 150, 20);
        add(labelTotalAntrian);

        listModel = new DefaultListModel<>();
        listAntrian = new JList<>(listModel);
        JScrollPane scrollPane = new JScrollPane(listAntrian);
        scrollPane.setBounds(10, 70, 150, 150);
        add(scrollPane);

        JButton btnAmbilNomor = new JButton("Ambil Nomor Antrian");
        btnAmbilNomor.setBounds(180, 10, 200, 30);
        btnAmbilNomor.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                enqueue(totalAntrian + 1);
                updateUI();
            }
        });
        add(btnAmbilNomor);

        JButton btnProsesAntrian = new JButton("Proses Antrian");
        btnProsesAntrian.setBounds(180, 50, 200, 30);
        btnProsesAntrian.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (ukuran() > 0) {
                    panggilanNomor = dequeue();
                    updateUI();
                }
            }
        });
        add(btnProsesAntrian);

        labelPanggilanNomor = new JLabel("Panggilan Nomor Antrian: -");
        labelPanggilanNomor.setBounds(180, 90, 200, 20);
        add(labelPanggilanNomor);

        setVisible(true);
    }

    @Override
    public void enqueue(int number) {
        antrian.add(number);
        totalAntrian++;
    }

    @Override
    public int dequeue() {
        if (!antrian.isEmpty()) {
            totalAntrian--;
            return antrian.poll();
        } else {
            return -1; // Antrian kosong
        }
    }

    
    @Override
    public int ukuran() {
        return totalAntrian;
    }

    private void updateUI() {
        labelJumlahAntrian.setText("Jumlah Antrian: " + ukuran());
        labelTotalAntrian.setText("Total Antrian: " + totalAntrian);
        labelPanggilanNomor.setText("Panggilan Nomor Antrian: " + panggilanNomor);

        listModel.clear();
        for (Integer nomorAntrian : antrian) {
            listModel.addElement(String.valueOf(nomorAntrian));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AntrianApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AntrianApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AntrianApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AntrianApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AntrianApp();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
